name: 'Format with Prettier'

on: 
  push:
    branches: [master]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'master'
      
      - name: Use NodeJS 14
        uses: actions/setup-node@v1

      - name: Format
        run: |
          npm install -g yarn
          cd $GITHUB_WORKSPACE && ls -la
          yarn install
          yarn format
      
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes to last push
